title: Udank Jain
logo: /img/GitHub.jpg
description: I’m a final-year student at IIT Bombay pursuing Bachelors of Technology (with Honours) in Civil Engineering with a minor in Management,  I am passionate about structural engineering and eager to deepen my understanding of its core concepts.
# show_downloads: true
theme: jekyll-theme-minimal
